# Generated by Django 4.0.4 on 2022-05-11 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_catalogitem_alter_shipment_item_delete_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatalogItem',
            new_name='CatalogEntry',
        ),
    ]
