# Generated by Django 4.0.4 on 2022-05-11 14:56

from django.db import migrations
import yaml


def create_default_cities(apps, schema_editor):
    """ Create default cities using config.
    """
    Country = apps.get_model('inventory', 'Country')
    City = apps.get_model('inventory', 'City')

    with open('shopify_dev_intern_challenge/config/cities.yml', 'r') as stream:
        try:
            result = yaml.safe_load(stream)
            if result.get('cities'):
                for city in result['cities']:
                    country, created = Country.objects.get_or_create(
                        name=city['country'])
                    City.objects.get_or_create(
                        name=city['name'], country=country)

        except yaml.YAMLError as exc:
            print(exc)
            return


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_catalogentry_city_country_inventoryitem_warehouse_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_cities),
    ]
