# Generated by Django 4.0.4 on 2022-05-11 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_catalogitem_catalogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.catalogentry')),
            ],
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
