# Generated by Django 4.0.4 on 2022-05-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20220511_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='location',
            new_name='warehouse',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='date',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
