# Generated by Django 4.0.4 on 2022-05-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_city_temp_city_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
